# プロフィール概要カードを生成するためのGitHub Actionsワークフロー
name: GitHub-Profile-Summary-Cards

# ワークフローをスケジュール、手動トリガー、または特定のパスを除外してmainにプッシュしたときにトリガー
on:
  schedule:
    - cron: "0 0 * * *" # daily at 00:00 UTC
  workflow_dispatch:
  push:
    branches: [main]
    paths-ignore:
      - "profile-summary-card-output/**"

# 必要な権限を設定
permissions:
  contents: write

# ジョブ定義
jobs:
  build:
    runs-on: ubuntu-latest
    name: generate
    steps:
      - uses: actions/checkout@v4
      - name: Generate profile summary cards (auto push)
        uses: vn7n24fzkq/github-profile-summary-cards@release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          USERNAME: ${{ github.repository_owner }}
          # BRANCH_NAMEは自動プッシュを受け取るブランチを制御
          BRANCH_NAME: "main"
          # UTC_OFFSETはオプションで、デフォルトはゼロ
          UTC_OFFSET: 9
          # EXCLUDEはオプションで、除外する言語のカンマ区切りリスト、デフォルトは""
          EXCLUDE: ""
          # 自動プッシュを有効にして、更新を直接mainに反映させる
          AUTO_PUSH: true
